### ISSUE TITLE
Footer isn't positioned at the bottom of screen on empty pages

### ISSUE THREAD

**Issue by soli-exe** [nimaprmdi/collaborate#4]
On pages without any elements or components,
Footer is placed at the bottom of header not screen!
That's caused something like if a component is not fit the max screen height, footer keeps it position under that component **NOT** at the very bottom of screen

**Comment by nimaprmdi** [comment]
@soli-exe 
Added page container logic to pages. Please use `o-page` > `o-page__container` class lists to achieve responsivenes. 

going to close issue. Thanks
